// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/1005281342/gozerodemo/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/demo/hello/say",
				Handler: SayHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/demo/tasks/add",
				Handler: AddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/demo/tasks/cancel",
				Handler: CancelHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/jaeger/node",
				Handler: Node1Handler(serverCtx),
			},
		},
	)
}
