// Code generated by goctl. DO NOT EDIT!
// Source: tasks.proto

package server

import (
	"context"

	"github.com/1005281342/gozerodemo/rpc/tasks/internal/logic"
	"github.com/1005281342/gozerodemo/rpc/tasks/internal/svc"
	"github.com/1005281342/gozerodemo/rpc/tasks/tasks"
)

type TasksServer struct {
	svcCtx *svc.ServiceContext
}

func NewTasksServer(svcCtx *svc.ServiceContext) *TasksServer {
	return &TasksServer{
		svcCtx: svcCtx,
	}
}

func (s *TasksServer) Add(ctx context.Context, in *tasks.AddReq) (*tasks.AddRsp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
